#!/bin/bash

do_backup() {
  clear
  echo "Fazendo backup..."
  cd /root/paineldtunnel || exit 1
  cp prisma/database.db /root/painelbackup || exit 1
  cp .env /root/painelbackup || exit 1
  zip -r /root/painelbackup.zip /root/painelbackup || exit 1
  echo
  echo "Backup salvo em /root/painelbackup.zip"
  echo
  exit 0
}

toggle_auto_backup() {
  clear
  read -p "DESEJA ATIVAR AUTO BACKUP? (s/n) " atb
  if [[ $atb = @(s|S) ]]; then
    echo "Ativando..."
    backmod
    echo
    echo "Backup a cada 5 horas ativado!"
    exit 0
  fi
  menudt
}

remove_panel() {
  clear
  read -p "DESEJA REMOVER PAINEL? (s/n) " rev
  if [[ $rev = @(s|S) ]]; then
    echo "Removendo..."
    poff
    rm /bin/pon /bin/poff /bin/menudt /bin/backmod
    rm -r /root/paineldtunnel
    echo "Removido com sucesso!"
    exit 0
  fi
  menudt
}

restore_backup() {
  clear
  if [[ ! -e /root/painelbackup.zip ]]; then
    echo "Arquivo painelbackup.zip não encontrado em /root"
    sleep 4
    menudt
  fi
  read -p "DESEJA RESTAURAR BACKUP? (s/n) " rapi
  if [[ $rapi = @(s|S) ]]; then
    echo "Restaurando..."
    cd /root/paineldtunnel || exit 1
    rm prisma/database.db .env || exit 1
    unzip /root/painelbackup.zip || exit 1
    mv /root/painelbackup/database.db prisma/ || exit 1
    mv /root/painelbackup/.env . || exit 1
    rm -r /root/painelbackup
    pon
    echo
    echo "Backup restaurado com sucesso!"
    exit 0
  elif [[ $rapi = @(n|N) ]]; then
    echo "Voltando para o menudt"
    sleep 2
    menudt
  fi
  menudt
}

menudt() {
  clear
  echo -e "\033[1;34m╔═════════════════════════════╗\033[0m"
  echo -e "\033[1;34m║\033[1;41m\033[1;32m  MENU PAINEL DTUNNEL-MOD    \033[0m\033[1;34m║"
  echo -e "\033[1;34m╠═════════════════════════════╣\033[0m" 
  echo -e "\033[1;34m║\033[1;36m[\033[1;32m01\033[1;36m] \033[1;32m• \033[1;31mFAZER BACKUP          \033[1;34m║"
  echo -e "\033[1;34m║\033[1;36m[\033[1;32m02\033[1;36m] \033[1;32m• \033[1;31mRESTAURAR BACKUP      \033[1;34m║"
  echo -e "\033[1;34m║\033[1;36m[\033[1;32m03\033[1;36m] \033[1;32m• \033[1;31mREINICIAR PAINEL      \033[1;34m║"
  echo -e "\033[1;34m║\033[1;36m[\033[1;32m04\033[1;36m] \033[1;32m• \033[1;31mATIVAR AUTO BACKUP    \033[1;34m║"
  echo -e "\033[1;34m║\033[1;36m[\033[1;32m05\033[1;36m] \033[1;32m• \033[1;31mREMOVER PAINEL        \033[1;34m║"
  echo -e "\033[1;34m║\033[1;36m[\033[1;32m07\033[1;36m] \033[1;32m• \033[1;31mSAIR                  \033[1;34m║"
  echo -e "\033[1;34m╠═════════════════════════════╝\033[0m"
  echo -ne "\033[1;34m╚➤ \033[1;31mINFORME UMA OPÇÃO \033[1;33m : "; 
  read resp
  case $resp in
    1) do_backup ;;
    2) restore_backup ;;
    3) clear; echo "Reiniciando..."; pon; echo "Reiniciado com sucesso!"; sleep 3 ;;
    4) toggle_auto_backup ;;
    5) remove_panel ;;
    0) echo "Saindo..."; exit 0 ;;
    *) echo "Opção inválida!"; sleep 3 ;;
  esac
}
menudt
