#!/bin/bash

do_backup() {
  clear
  echo "Fazendo backup..."
  cd /root/paineldtunnel
  #rm -r painelbackup > /dev/null
  #mkdir painelbackup > /dev/null
  cp prisma/database.db painelbackup
  cp .env painelbackup
  zip -r painelbackup.zip painelbackup
  mv painelbackup.zip /root
  echo
  echo "painelbackup.zip salvo em /root"
  echo
  exit 0
}
toggle_auto_backup() {
  clear
  read -p "DESEJA ATIVAR AUTO BACKUP? (s/n) " atb
  [[ $atb = @(s|S) ]] && {
    echo "Ativando...."
    backmod
    echo
    echo "Backup de 5 em 5 horas ativo!"
    exit 0
  }
  menudt
}
remove_panel() {
  clear
  read -p "DESEJA REMOVER O PAINEL? (s/n) " rev
  [[ $rev = @(s|S) ]] && {
    echo "Removendo..."
    poff
    rm /bin/pon /bin/poff /bin/menudt /bin/backmod
    rm -r /root/paineldtunnel
    echo "Removido com sucesso!"
    exit 0
  }
  menudt
}
restore_backup() {
  clear
  [[ ! -e /root/painelbackup.zip ]] && {
    echo "Arquivo painelbackup.zip não encontrado em /root"
    sleep 4
    menudt
  }
  read -p "Deseja Restaurar o Backup? (s/n) " rapi
  [[ $rapi = @(s|S) ]] && {
    echo "Restaurando..."
    cd /root/paineldtunnel
    rm prisma/database.db
    rm .env
    cd /root
    unzip painelbackup.zip
    cd painelbackup
    mv database.db ../paineldtunnel/prisma
    mv .env ../painelMod
    cd /root
    rm -r painelbackup
    pon
    echo
    echo "Backup restaurado com sucesso!"
    exit 0
  }
  [[ $rapi = @(n|N) ]] && {
    echo "Voltando para o menu"
    sleep 2
    menudt
  }
  menudt
}
#[[ ! -e /root/painelMod/src/index.ts ]] && exit 0
menudt() {
  clear
  echo -e "\033[1;34m╔═════════════════════════════╗\033[0m"
  echo -e "\033[1;34m║\033[1;41m\033[1;32m  MENU PAINEL DTUNNEL-MOD    \033[0m\033[1;34m║"
  echo -e "\033[1;34m╠═════════════════════════════╣\033[0m" 
  echo -e "\033[1;34m║\033[1;36m[\033[1;32m01\033[1;36m] \033[1;32m• \033[1;31mFAZER BACKUP          \033[1;34m║"
  echo -e "\033[1;34m║\033[1;36m[\033[1;32m02\033[1;36m] \033[1;32m• \033[1;31mRESTAURAR BACKUP      \033[1;34m║"
  echo -e "\033[1;34m║\033[1;36m[\033[1;32m03\033[1;36m] \033[1;32m• \033[1;31mREINICIAR PAINEL      \033[1;34m║"
  echo -e "\033[1;34m║\033[1;36m[\033[1;32m04\033[1;36m] \033[1;32m• \033[1;31mATIVAR AUTO BACKUP    \033[1;34m║"
  echo -e "\033[1;34m║\033[1;36m[\033[1;32m05\033[1;36m] \033[1;32m• \033[1;31mREMOVER PAINEL        \033[1;34m║"
  echo -e "\033[1;34m║\033[1;36m[\033[1;32m07\033[1;36m] \033[1;32m• \033[1;31mSAIR                  \033[1;34m║"
  echo -e "\033[1;34m╠═════════════════════════════╝\033[0m"
  echo -ne "\033[1;34m╚➤ \033[1;31mINFORME UMA OPÇÃO \033[1;33m : "; 
  read resp
  case $resp in
    1) 
    do_backup 
    sleep 3
    menudt
    ;;
    2) 
    restore_backup 
    sleep 3
    menudt
    ;;
    3) 
    clear
    echo "Reiniciando..."
    pon
    echo "Reiniciado com sucesso!"
    sleep 3
    menudt
    ;;
    4) 
    toggle_auto_backup 
    sleep 3
    menudt
    ;;
    5) 
    remove_panel 
    ;;
    0) 
    echo "Saindo..."
    exit 0 
    ;;
    *) 
    echo "Opção inválida!"
    sleep 3
    clear
    menudt
  esac
}
menudt
